/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.dzf.zxkj.platform.model.bdset;

import com.dzf.zxkj.base.model.SuperVO;
import com.dzf.zxkj.common.lang.DZFDate;
import com.dzf.zxkj.common.lang.DZFDateTime;
import com.dzf.zxkj.common.lang.DZFDouble;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <b> 凭证模板 </b>
 * <p>
 *     常用凭证
 * </p>
 * 创建日期:2014-09-19 00:43:31
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class PzmbhVO extends SuperVO {
	private static final long serialVersionUID = 3902288880635219195L;
	
	private DZFDateTime ts;
	
	@JsonProperty("mbbm")
	private String vtemplatecode ;
	
	@JsonProperty("mbmc")
	private String vtemplatename ;
	
	@JsonProperty("mbms")
	private String memo;
	
	@JsonProperty("user_id")
	private String coperatorid;
	
	@JsonProperty("dr")
	private Integer dr;
	
	@JsonProperty("date")
	private DZFDate doperatedate;
	
	@JsonProperty("pk_h_id")
	private String pk_corp_pztemplate_h;
	
	@JsonProperty("pk_gs")
	private String pk_corp ;

	private DZFDouble totalmny;
	
	public static final String TRANSFERNAME = "transfername";
	public static final String PK_TRADE_ACCOUNTSCHEMA = "pk_corp_accountschema";
	public static final String PK_TRANSFERINACCOUNT = "pk_transferinaccount";
	public static final String MEMO = "memo";
	public static final String COPERATORID = "coperatorid";
	public static final String ABSTRACTS = "abstracts";
	public static final String DOPERATEDATE = "doperatedate";
	public static final String TRANSFERCODE = "transfercode";
	public static final String PK_TRADE_TRANSTEMPLATE_H = "pk_corp_transtemplate_h";
			
  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2014-09-15 17:31:07
	 * @return DZFDateTime
	 */
	public DZFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2014-09-15 17:31:07
	 * @param newTs DZFDateTime
	 */
	public void setTs (DZFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	
	/**
	 * 属性memo的Getter方法.
	 * 创建日期:2014-09-15 17:31:07
	 * @return String
	 */
	public String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.
	 * 创建日期:2014-09-15 17:31:07
	 * @param newMemo String
	 */
	public void setMemo (String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性coperatorid的Getter方法.
	 * 创建日期:2014-09-15 17:31:07
	 * @return String
	 */
	public String getCoperatorid () {
		return coperatorid;
	}   
	/**
	 * 属性coperatorid的Setter方法.
	 * 创建日期:2014-09-15 17:31:07
	 * @param newCoperatorid String
	 */
	public void setCoperatorid (String newCoperatorid ) {
	 	this.coperatorid = newCoperatorid;
	} 	  
	
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2014-09-15 17:31:07
	 * @return DZFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2014-09-15 17:31:07
	 * @param newDr DZFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性doperatedate的Getter方法.
	 * 创建日期:2014-09-15 17:31:07
	 * @return DZFDate
	 */
	public DZFDate getDoperatedate () {
		return doperatedate;
	}   
	/**
	 * 属性doperatedate的Setter方法.
	 * 创建日期:2014-09-15 17:31:07
	 * @param newDoperatedate DZFDate
	 */
	public void setDoperatedate (DZFDate newDoperatedate ) {
	 	this.doperatedate = newDoperatedate;
	} 	  
	
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-09-15 17:31:07
	  * @return java.lang.String
	  */
	public String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-09-15 17:31:07
	  * @return java.lang.String
	  */
	public String getPKFieldName() {
	  return "pk_corp_pztemplate_h";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2014-09-15 17:31:07
	 * @return java.lang.String
	 */
	public String getTableName() {
		return "ynt_cppztemmb";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-09-15 17:31:07
	  */
     public PzmbhVO() {
		super();	
	}
	public String getPk_corp() {
		return pk_corp;
	}
	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}
	public String getPk_corp_pztemplate_h() {
		return pk_corp_pztemplate_h;
	}
	public void setPk_corp_pztemplate_h(String pk_corp_pztemplate_h) {
		this.pk_corp_pztemplate_h = pk_corp_pztemplate_h;
	}
	public String getVtemplatecode() {
		return vtemplatecode;
	}
	public void setVtemplatecode(String vtemplatecode) {
		this.vtemplatecode = vtemplatecode;
	}
	public String getVtemplatename() {
		return vtemplatename;
	}
	public void setVtemplatename(String vtemplatename) {
		this.vtemplatename = vtemplatename;
	}
	public DZFDouble getTotalmny() {
		return totalmny;
	}
	public void setTotalmny(DZFDouble totalmny) {
		this.totalmny = totalmny;
	}
} 
