/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.dzf.zxkj.platform.model.zncs;

import com.dzf.zxkj.common.lang.DZFBoolean;
import com.dzf.zxkj.common.lang.DZFDate;
import com.dzf.zxkj.common.lang.DZFDateTime;
import com.dzf.zxkj.common.model.SuperVO;
import com.fasterxml.jackson.annotation.JsonProperty;

@SuppressWarnings("serial")
public class BusiapplyBVO extends SuperVO {
	private static final long serialVersionUID = -7823717157973164802L;

	@JsonProperty("busiapplyid")
	private String pk_busiapply;
	
	@JsonProperty("busiapplybid")
	private String pk_busiapply_b;
	
	@JsonProperty("bdate")
	private DZFDate begindate;
	
	@JsonProperty("edate")
	private DZFDate enddate;
	
	@JsonProperty("customerid")
	private String pk_customer;
	
	@JsonProperty("customername")
	private String customername;
	
	@JsonProperty("customercode")
	private String customercode;
	
	@JsonProperty("apply")
	private DZFBoolean isapply;
	
	@JsonProperty("confim")
	private DZFBoolean isconfirm;
	
	@JsonProperty("state")
	private Integer vstatus;
	
	@JsonProperty("appdate")
	private DZFDate applydate;
	
	@JsonProperty("appid")
	private String applyoperatorid;
	
	@JsonProperty("condate")
	private DZFDate confirmdate;
	
	@JsonProperty("conid")
	private String confirmoperatorid;
	
	@JsonProperty("stdate")
	private DZFDate stopdate;
	
	@JsonProperty("stid")
	private String stopoperatorid;
	
	@JsonProperty("note")
	private String note;

	@JsonProperty("ts")
	private DZFDateTime ts;

	@JsonProperty("dr")
	private Integer dr;

	@JsonProperty("appname")
	private String applyoperatorname;//申请人名称
	@JsonProperty("conname")
	private String confirmoperatorname;//确认人名称
	@JsonProperty("stname")
	private String stopoperatorname;//终止人名称
	
	private String stopreason;//终止原因
	
	@JsonProperty("incode")
	private String innercode;//公司编码
	
	@JsonProperty("uname")
	private String unitname;//公司名称
	
	@JsonProperty("pk_gs")
	public String pk_corp;//公司主键和pk_customer一样
	
	public String getInnercode() {
		return innercode;
	}

	public void setInnercode(String innercode) {
		this.innercode = innercode;
	}

	public String getUnitname() {
		return unitname;
	}

	public void setUnitname(String unitname) {
		this.unitname = unitname;
	}

	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	public String getStopreason() {
		return stopreason;
	}

	public void setStopreason(String stopreason) {
		this.stopreason = stopreason;
	}
	public String getCustomercode() {
		return customercode;
	}

	public void setCustomercode(String customercode) {
		this.customercode = customercode;
	}

	public String getApplyoperatorname() {
		return applyoperatorname;
	}

	public void setApplyoperatorname(String applyoperatorname) {
		this.applyoperatorname = applyoperatorname;
	}

	public String getConfirmoperatorname() {
		return confirmoperatorname;
	}

	public void setConfirmoperatorname(String confirmoperatorname) {
		this.confirmoperatorname = confirmoperatorname;
	}

	public String getStopoperatorname() {
		return stopoperatorname;
	}

	public void setStopoperatorname(String stopoperatorname) {
		this.stopoperatorname = stopoperatorname;
	}

	public String getCustomername() {
		return customername;
	}

	public void setCustomername(String customername) {
		this.customername = customername;
	}

	public String getPk_busiapply() {
		return pk_busiapply;
	}

	public void setPk_busiapply(String pk_busiapply) {
		this.pk_busiapply = pk_busiapply;
	}

	public String getPk_busiapply_b() {
		return pk_busiapply_b;
	}

	public void setPk_busiapply_b(String pk_busiapply_b) {
		this.pk_busiapply_b = pk_busiapply_b;
	}

	public DZFDate getBegindate() {
		return begindate;
	}

	public void setBegindate(DZFDate begindate) {
		this.begindate = begindate;
	}

	public DZFDate getEnddate() {
		return enddate;
	}

	public void setEnddate(DZFDate enddate) {
		this.enddate = enddate;
	}

	public String getPk_customer() {
		return pk_customer;
	}

	public void setPk_customer(String pk_customer) {
		this.pk_customer = pk_customer;
	}

	public DZFBoolean getIsapply() {
		return isapply;
	}

	public void setIsapply(DZFBoolean isapply) {
		this.isapply = isapply;
	}

	public DZFBoolean getIsconfirm() {
		return isconfirm;
	}

	public void setIsconfirm(DZFBoolean isconfirm) {
		this.isconfirm = isconfirm;
	}

	public Integer getVstatus() {
		return vstatus;
	}

	public void setVstatus(Integer vstatus) {
		this.vstatus = vstatus;
	}

	public DZFDate getApplydate() {
		return applydate;
	}

	public void setApplydate(DZFDate applydate) {
		this.applydate = applydate;
	}

	public String getApplyoperatorid() {
		return applyoperatorid;
	}

	public void setApplyoperatorid(String applyoperatorid) {
		this.applyoperatorid = applyoperatorid;
	}

	public DZFDate getConfirmdate() {
		return confirmdate;
	}

	public void setConfirmdate(DZFDate confirmdate) {
		this.confirmdate = confirmdate;
	}

	public String getConfirmoperatorid() {
		return confirmoperatorid;
	}

	public void setConfirmoperatorid(String confirmoperatorid) {
		this.confirmoperatorid = confirmoperatorid;
	}

	public DZFDate getStopdate() {
		return stopdate;
	}

	public void setStopdate(DZFDate stopdate) {
		this.stopdate = stopdate;
	}

	public String getStopoperatorid() {
		return stopoperatorid;
	}

	public void setStopoperatorid(String stopoperatorid) {
		this.stopoperatorid = stopoperatorid;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public DZFDateTime getTs() {
		return ts;
	}

	public void setTs(DZFDateTime ts) {
		this.ts = ts;
	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2014-09-15 17:31:07
	 * 
	 * @return java.lang.String
	 */
	public String getParentPKFieldName() {
		return "pk_busiapply";
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2014-09-15 17:31:07
	 * 
	 * @return java.lang.String
	 */
	public String getPKFieldName() {
		return "pk_busiapply_b";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2014-09-15 17:31:07
	 * 
	 * @return java.lang.String
	 */
	public String getTableName() {
		return "fct_busiapply_b";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2014-09-15 17:31:07
	 */
	public BusiapplyBVO() {
		super();
	}
}
