package com.dzf.zxkj.platform.model.zncs;
/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/


import com.dzf.zxkj.common.lang.DZFDate;
import com.dzf.zxkj.common.lang.DZFDateTime;
import com.dzf.zxkj.common.model.SuperVO;
import com.fasterxml.jackson.annotation.JsonProperty;

@SuppressWarnings("serial")
public class BusiapplyHVO extends SuperVO {
	private static final long serialVersionUID = 7802288870635219195L;

	@JsonProperty("busiapplyid")
	private String pk_busiapply;

	@JsonProperty("contractno")
	private String contractnum;

	@JsonProperty("factoryid")
	private String accountfactoryid;

	@JsonProperty("factoryname")
	private String factoryname;//会计工厂名称
	
	private String factorycode;//会计工厂编码
	
	@JsonProperty("pk_factoryid")
	private String pk_factory;
	
	@JsonProperty("slevel")
	private Integer servicelevel;

	@JsonProperty("bcount")
	private Integer bodycount;
	
	@JsonProperty("appdate")
	private DZFDate applydate;

	@JsonProperty("appid")
	private String applyoperatorid;

	@JsonProperty("condate")
	private DZFDate confirmdate;
	
	@JsonProperty("conid")
	private String confirmoperatorid;
	
	@JsonProperty("stdate")
	private DZFDate stopdate;
	
	@JsonProperty("stid")
	private String stopoperatorid;
	
	@JsonProperty("edate")
	private DZFDate enddate;
	
	@JsonProperty("bdate")
	private DZFDate begindate;
	
	@JsonProperty("state")
	private Integer vstatus;
	
	@JsonProperty("aprid")
	private String approveid;
	
	@JsonProperty("aprdate")
	private DZFDate approvedate;
	
	@JsonProperty("chid")
	private String changeoperatorid;
	
	@JsonProperty("chdate")
	private DZFDate changedate;
	
	@JsonProperty("ts")
	private DZFDateTime ts;
	
	@JsonProperty("dr")
	private Integer dr;

	@JsonProperty("pk_corp")
	private String pk_corp;

	@JsonProperty("operid")
	private String coperatorid;

	@JsonProperty("operdate")
	private DZFDate doperatedate;

	@JsonProperty("opername")
	private String coperatorname;//制单人名称
	@JsonProperty("aprname")
	private String approvename;//审核人名称
	@JsonProperty("appname")
	private String applyoperatorname;//申请人名称
	@JsonProperty("conname")
	private String confirmoperatorname;//确认人名称
	@JsonProperty("stname")
	private String stopoperatorname;//终止人名称
	@JsonProperty("chname")
	private String changeoperatorname;//变更人
	
	@JsonProperty("accountcorpname")
	private String corpname;//会计公司名称
	
	@JsonProperty("accountcorpcode")
	private String corpcode;//会计公司编码
	
	private String stopreason;//终止原因
	
	@JsonProperty("scount")
	private Integer smallcount;//小规模户数
	
	@JsonProperty("gcount")
	private Integer generalcount;//一般人户数
	
	@JsonProperty("ncount")
	private Integer nocheckcount;//未核定户数
	
	private String period;//期间
	
	public String getPeriod() {
		return period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getFactorycode() {
		return factorycode;
	}

	public void setFactorycode(String factorycode) {
		this.factorycode = factorycode;
	}

	public Integer getNocheckcount() {
		return nocheckcount;
	}

	public void setNocheckcount(Integer nocheckcount) {
		this.nocheckcount = nocheckcount;
	}

	public Integer getSmallcount() {
		return smallcount;
	}

	public void setSmallcount(Integer smallcount) {
		this.smallcount = smallcount;
	}

	public Integer getGeneralcount() {
		return generalcount;
	}

	public void setGeneralcount(Integer generalcount) {
		this.generalcount = generalcount;
	}

	public String getStopreason() {
		return stopreason;
	}

	public void setStopreason(String stopreason) {
		this.stopreason = stopreason;
	}

	public Integer getServicelevel() {
		return servicelevel;
	}

	public void setServicelevel(Integer servicelevel) {
		this.servicelevel = servicelevel;
	}

	public String getCorpcode() {
		return corpcode;
	}

	public void setCorpcode(String corpcode) {
		this.corpcode = corpcode;
	}

	public String getCorpname() {
		return corpname;
	}

	public void setCorpname(String corpname) {
		this.corpname = corpname;
	}

	public String getChangeoperatorname() {
		return changeoperatorname;
	}

	public void setChangeoperatorname(String changeoperatorname) {
		this.changeoperatorname = changeoperatorname;
	}

	public String getCoperatorname() {
		return coperatorname;
	}

	public void setCoperatorname(String coperatorname) {
		this.coperatorname = coperatorname;
	}

	public String getApprovename() {
		return approvename;
	}

	public void setApprovename(String approvename) {
		this.approvename = approvename;
	}

	public String getApplyoperatorname() {
		return applyoperatorname;
	}

	public void setApplyoperatorname(String applyoperatorname) {
		this.applyoperatorname = applyoperatorname;
	}

	public String getConfirmoperatorname() {
		return confirmoperatorname;
	}

	public void setConfirmoperatorname(String confirmoperatorname) {
		this.confirmoperatorname = confirmoperatorname;
	}

	public String getStopoperatorname() {
		return stopoperatorname;
	}

	public void setStopoperatorname(String stopoperatorname) {
		this.stopoperatorname = stopoperatorname;
	}

	public String getPk_busiapply() {
		return pk_busiapply;
	}

	public void setPk_busiapply(String pk_busiapply) {
		this.pk_busiapply = pk_busiapply;
	}

	public String getContractnum() {
		return contractnum;
	}

	public void setContractnum(String contractnum) {
		this.contractnum = contractnum;
	}

	public String getAccountfactoryid() {
		return accountfactoryid;
	}

	public void setAccountfactoryid(String accountfactoryid) {
		this.accountfactoryid = accountfactoryid;
	}

	public String getPk_factory() {
		return pk_factory;
	}

	public void setPk_factory(String pk_factory) {
		this.pk_factory = pk_factory;
	}

	public String getFactoryname() {
		return factoryname;
	}

	public void setFactoryname(String factoryname) {
		this.factoryname = factoryname;
	}

	public Integer getBodycount() {
		return bodycount;
	}

	public void setBodycount(Integer bodycount) {
		this.bodycount = bodycount;
	}

	public DZFDate getApplydate() {
		return applydate;
	}

	public void setApplydate(DZFDate applydate) {
		this.applydate = applydate;
	}

	public String getApplyoperatorid() {
		return applyoperatorid;
	}

	public void setApplyoperatorid(String applyoperatorid) {
		this.applyoperatorid = applyoperatorid;
	}

	public DZFDate getConfirmdate() {
		return confirmdate;
	}

	public void setConfirmdate(DZFDate confirmdate) {
		this.confirmdate = confirmdate;
	}

	public String getConfirmoperatorid() {
		return confirmoperatorid;
	}

	public void setConfirmoperatorid(String confirmoperatorid) {
		this.confirmoperatorid = confirmoperatorid;
	}

	public DZFDate getStopdate() {
		return stopdate;
	}

	public void setStopdate(DZFDate stopdate) {
		this.stopdate = stopdate;
	}

	public String getStopoperatorid() {
		return stopoperatorid;
	}

	public void setStopoperatorid(String stopoperatorid) {
		this.stopoperatorid = stopoperatorid;
	}

	public DZFDate getEnddate() {
		return enddate;
	}

	public void setEnddate(DZFDate enddate) {
		this.enddate = enddate;
	}

	public DZFDate getBegindate() {
		return begindate;
	}

	public void setBegindate(DZFDate begindate) {
		this.begindate = begindate;
	}

	public Integer getVstatus() {
		return vstatus;
	}

	public void setVstatus(Integer vstatus) {
		this.vstatus = vstatus;
	}

	public String getApproveid() {
		return approveid;
	}

	public void setApproveid(String approveid) {
		this.approveid = approveid;
	}

	public DZFDate getApprovedate() {
		return approvedate;
	}

	public void setApprovedate(DZFDate approvedate) {
		this.approvedate = approvedate;
	}

	public String getChangeoperatorid() {
		return changeoperatorid;
	}

	public void setChangeoperatorid(String changeoperatorid) {
		this.changeoperatorid = changeoperatorid;
	}

	public DZFDate getChangedate() {
		return changedate;
	}

	public void setChangedate(DZFDate changedate) {
		this.changedate = changedate;
	}

	public DZFDateTime getTs() {
		return ts;
	}

	public void setTs(DZFDateTime ts) {
		this.ts = ts;
	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	public String getCoperatorid() {
		return coperatorid;
	}

	public void setCoperatorid(String coperatorid) {
		this.coperatorid = coperatorid;
	}

	public DZFDate getDoperatedate() {
		return doperatedate;
	}

	public void setDoperatedate(DZFDate doperatedate) {
		this.doperatedate = doperatedate;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2014-09-15 17:31:07
	 * 
	 * @return java.lang.String
	 */
	public String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2014-09-15 17:31:07
	 * 
	 * @return java.lang.String
	 */
	public String getPKFieldName() {
		return "pk_busiapply";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2014-09-15 17:31:07
	 * 
	 * @return java.lang.String
	 */
	public String getTableName() {
		return "fct_busiapply";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2014-09-15 17:31:07
	 */
	public BusiapplyHVO() {
		super();
	}

}
