/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package com.dzf.zxkj.platform.model.sys;

import com.dzf.zxkj.base.model.SuperVO;
import com.dzf.zxkj.common.lang.DZFBoolean;
import com.dzf.zxkj.common.lang.DZFDate;
import com.dzf.zxkj.common.lang.DZFDateTime;
import com.dzf.zxkj.common.lang.DZFDouble;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <b> 资产类别 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2014-09-15 17:25:49
 * @author Administrator
 * @version NCPrj 1.0
 */
public class BdAssetCategoryVO extends SuperVO<BdAssetCategoryVO> {
	private static final long serialVersionUID = 2903221711497305256L;
	private DZFDateTime ts;
	private String vdef9;
	@JsonProperty("cpid")
	private String coperatorid;
	private String vdef1;
	private String vdef8;
	private String vdef10;
	@JsonProperty("prop")
	private Integer assetproperty;
	private String vdef2;
	private String vdef5;
	@JsonProperty("name")
	private String catename;
	@JsonProperty("level")
	private Integer catelevel;
	@JsonProperty("memo")
	private String memo;
	private String vdef3;
	private String vdef6;
	@JsonProperty("dpdate")
	private DZFDate doperatedate;
	private Integer dr;
	private String vdef4;
	@JsonProperty("code")
	private String catecode;
	@JsonProperty("id")
	private String pk_assetcategory;
	private String vdef7;
	private DZFBoolean endflag; 
	@JsonProperty("corp")
	private String pk_corp;
	private String text;
	
	
	private Integer codeid;
	//private Integer __parentId;
	@JsonProperty("ulimit")
	private Integer uselimit;//预计使用年限
	
	@JsonProperty("zjfs")
	private Integer  zjtype;//折旧方式
	@JsonProperty("czl")
	private DZFDouble salvageratio;//残值率
	
	public static final String VDEF9 = "vdef9";
	public static final String COPERATORID = "coperatorid";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF10 = "vdef10";
	public static final String ASSETPROPERTY = "assetproperty";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF5 = "vdef5";
	public static final String CATENAME = "catename";
	public static final String CATELEVEL = "catelevel";
	public static final String MEMO = "memo";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF6 = "vdef6";
	public static final String DOPERATEDATE = "doperatedate";
	public static final String VDEF4 = "vdef4";
	public static final String CATECODE = "catecode";
	public static final String PK_ASSETCATEGORY = "pk_assetcategory";
	public static final String VDEF7 = "vdef7";
	
	
	
	public Integer getCodeid() {
		return codeid;
	}
	public void setCodeid(Integer codeid) {
		this.codeid = codeid;
	}
//	public Integer get__parentId() {
//		return __parentId;
//	}
//	public void set__parentId(Integer __parentId) {
//		this.__parentId = __parentId;
//	}
	
	
	public String getPk_corp() {
		return pk_corp;
	}
	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}
	public String toString() {
		return this.getCatecode()+" "+this.getCatename();
	}		
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return DZFDateTime
	 */
	public DZFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newTs DZFDateTime
	 */
	public void setTs (DZFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newVdef9 String
	 */
	public void setVdef9 (String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性coperatorid的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getCoperatorid () {
		return coperatorid;
	}   
	/**
	 * 属性coperatorid的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newCoperatorid String
	 */
	public void setCoperatorid (String newCoperatorid ) {
	 	this.coperatorid = newCoperatorid;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newVdef10 String
	 */
	public void setVdef10 (String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性assetproperty的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return UFDouble
	 */
	public Integer getAssetproperty () {
		return assetproperty;
	}   
	/**
	 * 属性assetproperty的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newAssetproperty UFDouble
	 */
	public void setAssetproperty (Integer newAssetproperty ) {
	 	this.assetproperty = newAssetproperty;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newVdef5 String
	 */
	public void setVdef5 (String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性catename的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getCatename () {
		return catename;
	}   
	/**
	 * 属性catename的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newCatename String
	 */
	public void setCatename (String newCatename ) {
	 	this.catename = newCatename;
	} 	  
	/**
	 * 属性catelevel的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return UFDouble
	 */
	public Integer getCatelevel () {
		return catelevel;
	}   
	/**
	 * 属性catelevel的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newCatelevel UFDouble
	 */
	public void setCatelevel (Integer newCatelevel ) {
	 	this.catelevel = newCatelevel;
	} 	  
	/**
	 * 属性memo的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newMemo String
	 */
	public void setMemo (String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newVdef6 String
	 */
	public void setVdef6 (String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性doperatedate的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return DZFDate
	 */
	public DZFDate getDoperatedate () {
		return doperatedate;
	}   
	/**
	 * 属性doperatedate的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newDoperatedate DZFDate
	 */
	public void setDoperatedate (DZFDate newDoperatedate ) {
	 	this.doperatedate = newDoperatedate;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newVdef4 String
	 */
	public void setVdef4 (String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性catecode的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getCatecode () {
		return catecode;
	}   
	/**
	 * 属性catecode的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newCatecode String
	 */
	public void setCatecode (String newCatecode ) {
	 	this.catecode = newCatecode;
	 	
//		this.codeid = new Integer(newCatecode);
//		if(newCatecode!=null&&newCatecode.length()>2){
//		this.__parentId = new Integer(newCatecode.substring(0, newCatecode.length()-2));
//		}else{
//			this.__parentId =null;
//		}
	 	
	} 	  
	/**
	 * 属性pk_assetcategory的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getPk_assetcategory () {
		return pk_assetcategory;
	}   
	/**
	 * 属性pk_assetcategory的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newPk_assetcategory String
	 */
	public void setPk_assetcategory (String newPk_assetcategory ) {
	 	this.pk_assetcategory = newPk_assetcategory;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @return String
	 */
	public String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2014-09-15 17:25:49
	 * @param newVdef7 String
	 */
	public void setVdef7 (String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  

	public DZFBoolean getEndflag() {
		return endflag;
	}
	public void setEndflag(DZFBoolean endflag) {
		this.endflag = endflag;
	}

	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-09-15 17:25:49
	  * @return java.lang.String
	  */
	public String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-09-15 17:25:49
	  * @return java.lang.String
	  */
	public String getPKFieldName() {
	  return "pk_assetcategory";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2014-09-15 17:25:49
	 * @return java.lang.String
	 */
	public String getTableName() {
		return "ynt_category";
	} 
    
    public Integer getUselimit() {
		return uselimit;
	}
	public void setUselimit(Integer uselimit) {
		this.uselimit = uselimit;
	}
	/**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-09-15 17:25:49
	  */
     public BdAssetCategoryVO() {
		super();	
	}
	public String getText() {
		text = getCatecode()+"_"+getCatename();
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public Integer getZjtype() {
		return zjtype;
	}
	public void setZjtype(Integer zjtype) {
		this.zjtype = zjtype;
	}
	public DZFDouble getSalvageratio() {
		return salvageratio;
	}
	public void setSalvageratio(DZFDouble salvageratio) {
		this.salvageratio = salvageratio;
	}

} 
