/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
 \***************************************************************/
package com.dzf.zxkj.platform.model.bdset;


import com.dzf.zxkj.common.model.SuperVO;
import com.dzf.zxkj.common.lang.DZFBoolean;
import com.dzf.zxkj.common.lang.DZFDateTime;
import com.dzf.zxkj.common.lang.DZFDouble;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <b> 凭证模板 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2014-09-19 00:43:31
 *
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class PzmbbVO extends SuperVO {
    private static final long serialVersionUID = -3323712154973164802L;

    private DZFDateTime ts;

    @JsonProperty("pk_b_id")
    private String pk_corp_pztemplate_b;

    //科目
    @JsonProperty("km")
    private String pk_accsubj;

    //科目编码
    @JsonProperty("kmbm")
    private String acccode;

    //摘要
    @JsonProperty("des")
    private String abstracts;

    @JsonProperty("dr")
    private Integer dr;

    @JsonProperty("pk_h_id")
    private String pk_corp_pztemplate_h;

    // 税目id
    private String pk_taxitem;
    private String taxcode;
    private String taxname;
    private DZFDouble taxratio;

    @JsonProperty("fx")
    private Integer direction;

    @JsonProperty("pk_gs")
    private String pk_corp;

    @JsonProperty("vcode")
    private String vcode;

    @JsonProperty("kmname")
    private String vname;

    @JsonProperty("fx1")
    private Integer direct;

    @JsonProperty("dj")
    private Integer vlevel;

    @JsonProperty("kmmc")
    private String subjname; //取数科目名称

    //add by zhangj不存库查询使用
    private DZFBoolean bisseal;
    private String accountcode;


    private String pk_currency;

    @JsonProperty("fzhs1")
    private String fzhsx1;//辅助核算客户
    @JsonProperty("fzhs2")
    private String fzhsx2;//辅助核算供应商
    @JsonProperty("fzhs3")
    private String fzhsx3;//辅助核算职员
    @JsonProperty("fzhs4")
    private String fzhsx4;//辅助核算供项目
    @JsonProperty("fzhs5")
    private String fzhsx5;//辅助核算部门
    @JsonProperty("fzhs6")
    private String fzhsx6;//辅助核算存货
    @JsonProperty("fzhs7")
    private String fzhsx7;//辅助核算自定义1
    @JsonProperty("fzhs8")
    private String fzhsx8;//辅助核算自定义2
    @JsonProperty("fzhs9")
    private String fzhsx9;//辅助核算自定义3
    @JsonProperty("fzhs10")
    private String fzhsx10;//辅助核算自定义4

    @JsonProperty("chid")
    //	存货ID
    private String pk_inventory;
    @JsonProperty("chbm")
    private String invcode;//存货编码
    @JsonProperty("chName")
    private String invname;//存货名称
    private String meacode;//计量单位编码

    @JsonProperty("jldw")
    private String meaname;//计量单位名称

    private DZFDouble mny;//金额

    //存货数量
    @JsonProperty("chnum")
    private DZFDouble nnumber;
    @JsonProperty("chdj")
    //存货单价
    private DZFDouble nprice;
    @JsonProperty("nrate")
    //汇率
    private DZFDouble nrate;
    @JsonProperty("ybmny")
    private DZFDouble ybmny;// 原币金额

    public String getPk_corp() {
        return pk_corp;
    }

    public void setPk_corp(String pk_corp) {
        this.pk_corp = pk_corp;
    }

    public Integer getDirection() {
        return direction;
    }

    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    /**
     * 属性ts的Getter方法.
     * 创建日期:2014-09-15 17:31:07
     *
     * @return DZFDateTime
     */
    public DZFDateTime getTs() {
        return ts;
    }

    /**
     * 属性ts的Setter方法.
     * 创建日期:2014-09-15 17:31:07
     *
     * @param newTs DZFDateTime
     */
    public void setTs(DZFDateTime newTs) {
        this.ts = newTs;
    }

    /**
     * 属性abstracts的Getter方法.
     * 创建日期:2014-09-15 17:31:07
     *
     * @return String
     */
    public String getAbstracts() {
        return abstracts;
    }

    /**
     * 属性abstracts的Setter方法.
     * 创建日期:2014-09-15 17:31:07
     *
     * @param newAbstracts String
     */
    public void setAbstracts(String newAbstracts) {
        this.abstracts = newAbstracts;
    }

    /**
     * 属性dr的Getter方法.
     * 创建日期:2014-09-15 17:31:07
     *
     * @return DZFDouble
     */
    public Integer getDr() {
        return dr;
    }

    /**
     * 属性dr的Setter方法.
     * 创建日期:2014-09-15 17:31:07
     *
     * @param newDr DZFDouble
     */
    public void setDr(Integer newDr) {
        this.dr = newDr;
    }


    /**
     * <p>取得父VO主键字段.
     * <p>
     * 创建日期:2014-09-15 17:31:07
     *
     * @return java.lang.String
     */
    public String getParentPKFieldName() {
        return "PK_CORP_PZTEMPLATE_H";
    }

    /**
     * <p>取得表主键.
     * <p>
     * 创建日期:2014-09-15 17:31:07
     *
     * @return java.lang.String
     */
    public String getPKFieldName() {
        return "pk_corp_pztemplate_b";
    }

    /**
     * <p>返回表名称.
     * <p>
     * 创建日期:2014-09-15 17:31:07
     *
     * @return java.lang.String
     */
    public String getTableName() {
        return "ynt_cppztemmb_b";
    }

    /**
     * 按照默认方式创建构造子.
     * <p>
     * 创建日期:2014-09-15 17:31:07
     */
    public PzmbbVO() {
        super();
    }

    public String getPk_accsubj() {
        return pk_accsubj;
    }

    public void setPk_accsubj(String pk_accsubj) {
        this.pk_accsubj = pk_accsubj;
    }

    public String getPk_corp_pztemplate_b() {
        return pk_corp_pztemplate_b;
    }

    public void setPk_corp_pztemplate_b(String pk_corp_pztemplate_b) {
        this.pk_corp_pztemplate_b = pk_corp_pztemplate_b;
    }

    public String getPk_corp_pztemplate_h() {
        return pk_corp_pztemplate_h;
    }

    public void setPk_corp_pztemplate_h(String pk_corp_pztemplate_h) {
        this.pk_corp_pztemplate_h = pk_corp_pztemplate_h;
    }

    public String getPk_taxitem() {
        return pk_taxitem;
    }

    public void setPk_taxitem(String pk_taxitem) {
        this.pk_taxitem = pk_taxitem;
    }

    public String getTaxcode() {
        return taxcode;
    }

    public void setTaxcode(String taxcode) {
        this.taxcode = taxcode;
    }

    public String getTaxname() {
        return taxname;
    }

    public void setTaxname(String taxname) {
        this.taxname = taxname;
    }

    public DZFDouble getTaxratio() {
        return taxratio;
    }

    public void setTaxratio(DZFDouble taxratio) {
        this.taxratio = taxratio;
    }

    public String getAcccode() {
        return acccode;
    }

    public void setAcccode(String acccode) {
        this.acccode = acccode;
    }

    public String getVcode() {
        return vcode;
    }

    public void setVcode(String vcode) {
        this.vcode = vcode;
    }

    public String getVname() {
        return vname;
    }

    public void setVname(String vname) {
        this.vname = vname;
    }

    public Integer getDirect() {
        return direct;
    }

    public void setDirect(Integer direct) {
        this.direct = direct;
    }

    public Integer getVlevel() {
        return vlevel;
    }

    public void setVlevel(Integer vlevel) {
        this.vlevel = vlevel;
    }

    public String getAccountcode() {
        return accountcode;
    }

    public void setAccountcode(String accountcode) {
        this.accountcode = accountcode;
    }

    public DZFBoolean getBisseal() {
        return bisseal;
    }

    public void setBisseal(DZFBoolean bisseal) {
        this.bisseal = bisseal;
    }

    public String getPk_currency() {
        return pk_currency;
    }

    public void setPk_currency(String pk_currency) {
        this.pk_currency = pk_currency;
    }

    public String getSubjname() {
        return subjname;
    }

    public void setSubjname(String subjname) {
        this.subjname = subjname;
    }

    public String getFzhsx1() {
        return fzhsx1;
    }

    public void setFzhsx1(String fzhsx1) {
        this.fzhsx1 = fzhsx1;
    }

    public String getFzhsx2() {
        return fzhsx2;
    }

    public void setFzhsx2(String fzhsx2) {
        this.fzhsx2 = fzhsx2;
    }

    public String getFzhsx3() {
        return fzhsx3;
    }

    public void setFzhsx3(String fzhsx3) {
        this.fzhsx3 = fzhsx3;
    }

    public String getFzhsx4() {
        return fzhsx4;
    }

    public void setFzhsx4(String fzhsx4) {
        this.fzhsx4 = fzhsx4;
    }

    public String getFzhsx5() {
        return fzhsx5;
    }

    public void setFzhsx5(String fzhsx5) {
        this.fzhsx5 = fzhsx5;
    }

    public String getFzhsx6() {
        return fzhsx6;
    }

    public void setFzhsx6(String fzhsx6) {
        this.fzhsx6 = fzhsx6;
    }

    public String getFzhsx7() {
        return fzhsx7;
    }

    public void setFzhsx7(String fzhsx7) {
        this.fzhsx7 = fzhsx7;
    }

    public String getFzhsx8() {
        return fzhsx8;
    }

    public void setFzhsx8(String fzhsx8) {
        this.fzhsx8 = fzhsx8;
    }

    public String getFzhsx9() {
        return fzhsx9;
    }

    public void setFzhsx9(String fzhsx9) {
        this.fzhsx9 = fzhsx9;
    }

    public String getFzhsx10() {
        return fzhsx10;
    }

    public void setFzhsx10(String fzhsx10) {
        this.fzhsx10 = fzhsx10;
    }

    public String getPk_inventory() {
        return pk_inventory;
    }

    public void setPk_inventory(String pk_inventory) {
        this.pk_inventory = pk_inventory;
    }

    public String getInvcode() {
        return invcode;
    }

    public void setInvcode(String invcode) {
        this.invcode = invcode;
    }

    public String getInvname() {
        return invname;
    }

    public void setInvname(String invname) {
        this.invname = invname;
    }

    public String getMeacode() {
        return meacode;
    }

    public void setMeacode(String meacode) {
        this.meacode = meacode;
    }

    public String getMeaname() {
        return meaname;
    }

    public void setMeaname(String meaname) {
        this.meaname = meaname;
    }

    public DZFDouble getMny() {
        return mny;
    }

    public void setMny(DZFDouble mny) {
        this.mny = mny;
    }

    public DZFDouble getNnumber() {
        return nnumber;
    }

    public void setNnumber(DZFDouble nnumber) {
        this.nnumber = nnumber;
    }

    public DZFDouble getNprice() {
        return nprice;
    }

    public void setNprice(DZFDouble nprice) {
        this.nprice = nprice;
    }

    public DZFDouble getNrate() {
        return nrate;
    }

    public void setNrate(DZFDouble nrate) {
        this.nrate = nrate;
    }

    public DZFDouble getYbmny() {
        return ybmny;
    }

    public void setYbmny(DZFDouble ybmny) {
        this.ybmny = ybmny;
    }

} 
