package com.dzf.zxkj.platform.model.jzcl;

/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/

import com.dzf.zxkj.base.model.SuperVO;
import com.dzf.zxkj.common.lang.DZFBoolean;
import com.dzf.zxkj.common.lang.DZFDate;
import com.dzf.zxkj.common.lang.DZFDateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * 固定资产结账
 * @author Administrator
 */
@SuppressWarnings("serial")
public class GdzcjzVO extends SuperVO {
	@JsonProperty("id_corp")
	private String pk_corp;
	@JsonProperty("ts")
	private DZFDateTime ts;
	@JsonProperty("vf9")
	private String vdef9;
	@JsonProperty("coid")
	private String coperatorid;
	@JsonProperty("id_gdzcjz")
	private String pk_gdzcjz;
	@JsonProperty("vf1")
	private String vdef1;
	@JsonProperty("vf8")
	private String vdef8;
	@JsonProperty("vf10")
	private String vdef10;
	@JsonProperty("piod")
	public String period;
	@JsonProperty("vapprid")
	private String vapproveid;
	@JsonProperty("vappnote")
	private String vapprovenote;
	@JsonProperty("hdsytz")
	private DZFBoolean ishdsytz;
	@JsonProperty("cbjz")
	public DZFBoolean iscbjz;
	@JsonProperty("vf7")
	private String vdef7;
	@JsonProperty("finish")
	public DZFBoolean jzfinish;
	@JsonProperty("dappdate")
	private DZFDate dapprovedate;
	@JsonProperty("vf2")
	private String vdef2;
	@JsonProperty("vf5")
	private String vdef5;
	@JsonProperty("qjsyjz")
	public DZFBoolean isqjsyjz;
	@JsonProperty("id_billtype")
	private String pk_billtype;
	@JsonProperty("vstatus")
	private Integer vbillstatus;
	@JsonProperty("memo")
	private String memo;
	@JsonProperty("vf3")
	private String vdef3;
	@JsonProperty("vf6")
	private String vdef6;
	@JsonProperty("vno")
	private String vbillno;
	@JsonProperty("dr")
	private Integer dr;
	@JsonProperty("ddate")
	private DZFDate doperatedate;
	@JsonProperty("gdzjjz")
	public DZFBoolean isgdzjjz;
	@JsonProperty("zjjt")
	public DZFBoolean iszjjt;
	@JsonProperty("vf4")
	private String vdef4;
	@JsonProperty("unitname")
	public String unitname;
	
	private String uptrow;
	//打印时  标题显示的区间区间
	public String titlePeriod;
	// 公司
	public String gs;

	public static final String PK_CORP = "pk_corp";
	public static final String VDEF9 = "vdef9";
	public static final String COPERATORID = "coperatorid";
	public static final String PK_GDZCJZ = "pk_gdzcjz";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF10 = "vdef10";
	public static final String PERIOD = "period";
	public static final String VAPPROVEID = "vapproveid";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String ISHDSYTZ = "ishdsytz";
	public static final String ISCBJZ = "iscbjz";
	public static final String VDEF7 = "vdef7";
	public static final String JZFINISH = "jzfinish";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF5 = "vdef5";
	public static final String ISQJSYJZ = "isqjsyjz";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String MEMO = "memo";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF6 = "vdef6";
	public static final String VBILLNO = "vbillno";
	public static final String DOPERATEDATE = "doperatedate";
	public static final String ISGDZJJZ = "isgdzjjz";
	public static final String ISZJJT = "iszjjt";
	public static final String VDEF4 = "vdef4";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return DZFDateTime
	 */
	public DZFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newTs DZFDateTime
	 */
	public void setTs (DZFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVdef9 String
	 */
	public void setVdef9 (String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性coperatorid的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getCoperatorid () {
		return coperatorid;
	}   
	/**
	 * 属性coperatorid的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newCoperatorid String
	 */
	public void setCoperatorid (String newCoperatorid ) {
	 	this.coperatorid = newCoperatorid;
	} 	  
	/**
	 * 属性pk_gdzcjz的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getPk_gdzcjz () {
		return pk_gdzcjz;
	}   
	/**
	 * 属性pk_gdzcjz的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newPk_gdzcjz String
	 */
	public void setPk_gdzcjz (String newPk_gdzcjz ) {
	 	this.pk_gdzcjz = newPk_gdzcjz;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVdef10 String
	 */
	public void setVdef10 (String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性period的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getPeriod () {
		return period;
	}   
	/**
	 * 属性period的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newPeriod String
	 */
	public void setPeriod (String newPeriod ) {
	 	this.period = newPeriod;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性vapprovenote的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVapprovenote () {
		return vapprovenote;
	}   
	/**
	 * 属性vapprovenote的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVapprovenote String
	 */
	public void setVapprovenote (String newVapprovenote ) {
	 	this.vapprovenote = newVapprovenote;
	} 	  
	/**
	 * 属性ishdsytz的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return DZFBoolean
	 */
	public DZFBoolean getIshdsytz () {
		return ishdsytz;
	}   
	/**
	 * 属性ishdsytz的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newIshdsytz DZFBoolean
	 */
	public void setIshdsytz (DZFBoolean newIshdsytz ) {
	 	this.ishdsytz = newIshdsytz;
	} 	  
	/**
	 * 属性iscbjz的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return DZFBoolean
	 */
	public DZFBoolean getIscbjz () {
		return iscbjz;
	}   
	/**
	 * 属性iscbjz的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newIscbjz DZFBoolean
	 */
	public void setIscbjz (DZFBoolean newIscbjz ) {
	 	this.iscbjz = newIscbjz;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVdef7 String
	 */
	public void setVdef7 (String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性jzfinish的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return DZFBoolean
	 */
	public DZFBoolean getJzfinish () {
		return jzfinish;
	}   
	/**
	 * 属性jzfinish的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newJzfinish DZFBoolean
	 */
	public void setJzfinish (DZFBoolean newJzfinish ) {
	 	this.jzfinish = newJzfinish;
	} 	  
	/**
	 * 属性dapprovedate的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return DZFDate
	 */
	public DZFDate getDapprovedate () {
		return dapprovedate;
	}   
	/**
	 * 属性dapprovedate的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newDapprovedate DZFDate
	 */
	public void setDapprovedate (DZFDate newDapprovedate ) {
	 	this.dapprovedate = newDapprovedate;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVdef5 String
	 */
	public void setVdef5 (String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性isqjsyjz的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return DZFBoolean
	 */
	public DZFBoolean getIsqjsyjz () {
		return isqjsyjz;
	}   
	/**
	 * 属性isqjsyjz的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newIsqjsyjz DZFBoolean
	 */
	public void setIsqjsyjz (DZFBoolean newIsqjsyjz ) {
	 	this.isqjsyjz = newIsqjsyjz;
	} 	  
	/**
	 * 属性pk_billtype的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getPk_billtype () {
		return pk_billtype;
	}   
	/**
	 * 属性pk_billtype的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newPk_billtype String
	 */
	public void setPk_billtype (String newPk_billtype ) {
	 	this.pk_billtype = newPk_billtype;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return UFDouble
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVbillstatus UFDouble
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性memo的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newMemo String
	 */
	public void setMemo (String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVdef6 String
	 */
	public void setVdef6 (String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性vbillno的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVbillno () {
		return vbillno;
	}   
	/**
	 * 属性vbillno的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVbillno String
	 */
	public void setVbillno (String newVbillno ) {
	 	this.vbillno = newVbillno;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性doperatedate的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return DZFDate
	 */
	public DZFDate getDoperatedate () {
		return doperatedate;
	}   
	/**
	 * 属性doperatedate的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newDoperatedate DZFDate
	 */
	public void setDoperatedate (DZFDate newDoperatedate ) {
	 	this.doperatedate = newDoperatedate;
	} 	  
	/**
	 * 属性isgdzjjz的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return DZFBoolean
	 */
	public DZFBoolean getIsgdzjjz () {
		return isgdzjjz;
	}   
	/**
	 * 属性isgdzjjz的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newIsgdzjjz DZFBoolean
	 */
	public void setIsgdzjjz (DZFBoolean newIsgdzjjz ) {
	 	this.isgdzjjz = newIsgdzjjz;
	} 	  
	/**
	 * 属性iszjjt的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return DZFBoolean
	 */
	public DZFBoolean getIszjjt () {
		return iszjjt;
	}   
	/**
	 * 属性iszjjt的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newIszjjt DZFBoolean
	 */
	public void setIszjjt (DZFBoolean newIszjjt ) {
	 	this.iszjjt = newIszjjt;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @return String
	 */
	public String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2014-11-04 15:45:39
	 * @param newVdef4 String
	 */
	public void setVdef4 (String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-11-04 15:45:39
	  * @return java.lang.String
	  */
	public String getParentPKFieldName() {
	    return null;
	}

	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-11-04 15:45:39
	  * @return java.lang.String
	  */
	public String getPKFieldName() {
	  return "pk_gdzcjz";
	}

	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2014-11-04 15:45:39
	 * @return java.lang.String
	 */
	public String getTableName() {
		return "YNT_GDZCJZ";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-11-04 15:45:39
	  */
     public GdzcjzVO() {
		super();	
	}
	public String getUnitname() {
		return unitname;
	}
	public void setUnitname(String unitname) {
		this.unitname = unitname;
	}
	public String getUptrow() {
		return uptrow;
	}
	public void setUptrow(String uptrow) {
		this.uptrow = uptrow;
	}
	public String getTitlePeriod() {
		return titlePeriod;
	}
	public void setTitlePeriod(String titlePeriod) {
		this.titlePeriod = titlePeriod;
	}
	public String getGs() {
		return gs;
	}
	public void setGs(String gs) {
		this.gs = gs;
	}
    
} 
